### ISSUE TITLE
1.16.5 server crashes when adding this mod

### ISSUE THREAD

**Issue by MateoCignetti** [DevEkode/FabricLockette#11]
Fabric server with only Fabric API and this mod crashes, here's the latest log:
[latest.log](https://github.com/DevEkode/FabricLockette/files/6446594/latest.log)

**Comment by DevEkode** [comment]
Hi ! Could you use the following bug report template ? It will help me to fix more easily your issue : https://github.com/DevEkode/FabricLockette/issues/new?labels=bug&template=bug_report.md

Thanks !
