### ISSUE TITLE
Server crashes when trying to lock a chest

### ISSUE THREAD

**Issue by MateoCignetti** [DevEkode/FabricLockette#14]
**Describe the bug**
When adding a sign to a chest and adding [Private] on the first line and a name on the second, the server crashes.
My server only has fabric API and this mod installed.

**To Reproduce**
1. Install Fabric Server with Fabric API and FabricLockette
2. Run server
3. Enter server and place a chest
4. Put a sign on the chest and try to lock it by writing [Private] on the first line and your name on the second

**Expected behavior**
The chest locks, only available to be opened by me. Server doesn't crash

**Environnement versions:**
 - Minecraft version : 1.16.5
 - FabricLockette version : 0.2.0

**Additional context**
[2021-05-11-2.log](https://github.com/DevEkode/FabricLockette/files/6461501/2021-05-11-2.log)

**Comment**
Kudos for fixing the crash when adding the mod! Hope this can be fixed as well, love your work!

**Comment by DevEkode** [comment]
Hey ! I'm a bit late on this topic.
Check out the last release v0.2.1, it should fix your issue.
