### ISSUE TITLE
Update for minecraft 1.18 ?

### ISSUE THREAD

**Issue by Maxtar07** [DevEkode/FabricLockette#22]
Hi ! I don't know if you plan to update it for the new versions of minecraft but it would be really great. I'm currently looking for a mod for my server that allows to lock some blocks and that's perfectly what your mod offers. But I need it for the 1.18 version of minecraft

**Comment by DevEkode** [comment]
Hey ! I plan to support 1.16, 1.17 and 1.18 of course. But this will need a bit for work.
My free time is a bit limited right now but I'll start working on it asap 😄

**Comment by Maxtar07** [comment]
thank you for your answer!

**Comment by DevEkode** [comment]
The new release is up and support Minecraft 1.18 (you can find it in the release page or on curseforge).
Have a nice day !
